import source_1 from '../assets/images/mock/products/1.jpg';
import source_2 from '../assets/images/mock/products/2.jpg';
import source_3 from '../assets/images/mock/products/3.jpg';
import source_4 from '../assets/images/mock/products/4.jpg';
import source_5 from '../assets/images/mock/products/5.jpg';
import source_6 from '../assets/images/mock/products/6.jpg';
import source_7 from '../assets/images/mock/products/7.jpg';
import source_8 from '../assets/images/mock/products/8.jpg';
import source_9 from '../assets/images/mock/products/9.jpg';
import source_10 from '../assets/images/mock/products/10.jpg';


export const products = [
  {
    id: '1',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_1,
  },
  {
    id: '2',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_2,
  },
  {
    id: '3',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_3,
  },
  {
    id: '4',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_4,
  },
  {
    id: '5',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_5,
  },
  {
    id: '6',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_6,
  },
  {
    id: '7',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_7,
  },
  {
    id: '8',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_8,
  },
  {
    id: '9',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_9,
  },
  {
    id: '10',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_10,
  },
  {
    id: '11',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_4,
  },
  {
    id: '12',
    name: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    price: 499,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_2,
  },
];
