import source_1 from '../assets/images/mock/products/1.jpg';
import source_2 from '../assets/images/mock/products/2.jpg';
import source_3 from '../assets/images/mock/products/3.jpg';
import source_4 from '../assets/images/mock/products/4.jpg';
import source_5 from '../assets/images/mock/products/5.jpg';
import source_6 from '../assets/images/mock/products/6.jpg';
import source_7 from '../assets/images/mock/products/7.jpg';
import source_8 from '../assets/images/mock/products/8.jpg';
import source_9 from '../assets/images/mock/products/9.jpg';
import source_10 from '../assets/images/mock/products/10.jpg';


export const products = [
  {
    id: '1',
    name: 'Laptop Dell Vostro 15 3500 (N3001VN3500UA03_2201_UBU) Black',
    price: 500,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_1,
  },
  {
    id: '2',
    name: 'Laptop HP ZBook Fury 17 G7 (9VE95AV_V4) Silver',
    price: 600,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_2,
  },
  {
    id: '3',
    name: 'Laptop ASUS TUF Gaming F15 FX506HCB-HN161 (90NR0723-M04940) Eclipse Gray',
    price: 499,
    discount_price: 333,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_3,
  },
  {
    id: '4',
    name: 'Laptop Acer Nitro 5 AN517-52-50DD (NH.QDVEU.00K) Obsidian Black',
    price: 545,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_4,
  },
  {
    id: '5',
    name: 'Laptop Acer Swift 5 SF514-55TA-55U6 (NX.A6SEU.005) Mist Green',
    price: 499,
    discount_price: 399,
    currency: 'USD',
    in_stock: false,
    review_score: 4.5,
    review_count: 4,
    source: source_5,
  },
  {
    id: '6',
    name: 'Laptop ASUS ZenBook 14 UM425QA-KI080 (90NB0TV1-M02230) Pine Grey',
    price: 950,
    discount_price: 700,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_6,
  },
  {
    id: '7',
    name: 'Laptop HP Envy 13-ba1012ua (4A7L7EA) Silver',
    price: 600,
    discount_price: 499,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_7,
  },
  {
    id: '8',
    name: 'Laptop ASUS ExpertBook B1 B1400CEAE-EB3492 14" IPS (90NX0421-M00BB0) Black / Intel Celeron 6305 / SSD 256 ГБ',
    price: 1025,
    discount_price: 870,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_8,
  },
  {
    id: '9',
    name: 'Laptop Apple MacBook Air 13" M1 256GB 2020 (MGN63) Space Gray',
    price: 499,
    discount_price: 350,
    currency: 'USD',
    in_stock: false,
    review_score: 4.5,
    review_count: 4,
    source: source_9,
  },
  {
    id: '10',
    name: 'Laptop Honor MagicBook X 15 (BBR-WAI9A) Space Grey',
    price: 499,
    discount_price: 375,
    currency: 'USD',
    in_stock: true,
    review_score: 4.5,
    review_count: 4,
    source: source_10,
  },
  {
    id: '11',
    name: 'Laptop Acer Aspire 5 A517-52G-31DC (NX.A5HEU.00T) Pure Silver',
    price: 545,
    discount_price: 499,
    currency: 'USD',
    in_stock: false,
    review_score: 4.5,
    review_count: 4,
    source: source_4,
  },
  {
    id: '12',
    name: 'Laptop Lenovo IdeaPad 3 14ITL6 (82H700L0RA) Arctic Grey',
    price: 1299,
    discount_price: 999,
    currency: 'USD',
    in_stock: false,
    review_score: 4.5,
    review_count: 4,
    source: source_2,
  },
];
